### ISSUE TITLE
Add to main clients list?

### ISSUE THREAD

**Issue by bl-ue** [vladimyr/tldr-lite#42]
Hey! I've never seen this!  Do you mind if I add it to the [clients list](https://github.com/tldr-pages/tldr#how-do-i-use-it)?

**Comment by vladimyr** [comment]
Go ahead but be aware that it intentionally diverges from spec by using Github's API directly without any caching layer.

**Comment by bl-ue** [comment]
In that case then I think I'll not, because we're working on getting rid of such clients from our list 🙂 (https://github.com/tldr-pages/tldr/issues/4044)
